Support new sdk
Zondax/ledger-oasis pull request #148
Opened 2021-12-22 18:05 UTC by ftheirs

Solves https://github.com/Zondax/ledger-oasis/issues/147

2021-12-22 21:09 UTC, jleni commented
@ftheirs 
I think we need to upgrade this project to GitHub actions now... so we can deprecate CircleCI also here
That is probably the reason it is failing

2021-12-23 11:59 UTC, matevz commented
Tested and the PR works. Just rebase to latest master please, otherwise the code doesn't compile.

2021-12-28 22:18 UTC, jleni requested changes

2021-12-28 22:18 UTC, jleni commented on app/Makefile
>  APPVERSION_P=1
Could you bump the version number?
we need this before we can merge

2021-12-30 17:10 UTC, merged