Submodules update
Zondax/ledger-oasis pull request #172
Opened 2022-06-17 16:11 UTC by chcmedeiros

2022-06-17 21:42 UTC, jleni requested changes
Version needs to be bumped before we can merge

2022-06-20 11:15 UTC, ftheirs approved these changes

2022-07-18 16:15 UTC, ftheirs commented
@jleni we need you approval to merge

2022-07-29 11:24 UTC, ftheirs approved these changes

2022-08-18 15:16 UTC, jleni approved these changes

2022-08-18 15:16 UTC, merged